### PR TITLE
Relax Rails version to < 5

### PR DESCRIPTION
**Pull request by adzap**
Exploring this gem further now, looks very promising. But the Rails version was locked at < 4 which wasn't there previously. This fixes that.

### CODE REVIEW

**Comment by dvandersluis** [comment]
Can you add a test for why the numeric? helper change was necessary? I'm ok with replacing monkey patches but would like it documented through specs.

Also, this change seems to have broken compatibility with 1.9.3 and 2.0, probably because it's installing the wrong version of rails.

Finally, I seem to remember that a Rails 3 feature was being used that isn't in Rails 4, but I can't remember what it is. I haven't tested explicitly in R4, so we might have to fix some bugs.

**Comment by adzap** [comment]
Sorry about that. The monkey patch removal was was not meant to be in that PR. please ignore for the moment.
On Tue, Feb 7, 2017 at 6:40 AM, Daniel Vandersluis <notifications@github.com> wrote:
Can you add a test for why the numeric? helper change was necessary? I'm ok with replacing monkey patches but would like it documented through specs.

Also, this change seems to have broken compatibility with 1.9.3 and 2.0, probably because it's installing the wrong version of rails.

Finally, I seem to remember that a Rails 3 feature was being used that isn't in Rails 4, but I can't remember what it is. I haven't tested explicitly in R4, so we might have to fix some bugs.

**Comment by adzap** [comment]
On the issue of build failures, I noticed the builds that failed are for Ruby 1.9 and 2.0 which are no longer supported. Do you still want these to be supported for the gem?

**Comment by dvandersluis** [comment]
Looks like a bunch of commits are being added to this PR -- some cool stuff, but I don't think you intended to mash them all into the same PR (if at all). Wouldn't mind making some of these changes if you want to make some individual PRs, but I'm going to close this for now.

Also, in terms of build errors, I want to keep supporting 1.9.3 and 2.0 for now despite being EOL'ed.

**Comment by adzap** [comment]
You're right I had forgotten about the PR. Please close it.

These are few rushed additions to see how it shapes up for my needs.

**Pull request closed without merging**
